### ISSUE TITLE
More Feedback

### ISSUE THREAD

**Issue by ifielker** [deep-rock-development/auto-stop-firebase-ext#2]
Congrats on your first extension! :) Here are some tips that might be helpful:

* The onInstall and onUpdate lifecycle functions in the extension.yaml can be the same function. So you can just move the installExtension logic into the onInstallExtension function, and then remove installExtension and onUpdateExtension functions and update your yaml to have onInstallExtension for both lifecycleEvents. (It will save you 2 unnecessary function definitions.)

* In installExtension you set the processing state to "NONE". This is not how the processing state was meant to be used. 
(https://firebase.google.com/docs/extensions/publishers/lifecycle-events#set-processing-state). While your task is actually running it is recommended to have the "PROCESSING" state so people can see that something is happening. (This state is set automatically for you). Then when the task is done you set either the success or failure. "None" is meant for either "The task started, but no processing was required and therefore there is nothing to report", or "processing finished a long time ago, and this status is not longer useful, so we clear it". I would recommend just removing that line where you set it to NONE so you can see that processing is happening until it's done.

**Comment by keston-4** [comment]
This is awesome thank you so much, I'm going back through with a fresh pair of eyes and addressing this :) Really appreciate your feedback.

**Comment by keston-4** [comment]
Resolved in #3 

Thank you again for your feedback!
